import { useState } from "react"; import type { Campaign, GrammarTopic, Scene, ValidationResult, VocabularyItem } from "../../types/gameTypes"; import { SceneEditor } from "./SceneEditor"; import { ValidationPanel } from "./ValidationPanel"; import { editorApi } from "../../api/editorApi"; import { useSettingsStore } from "../../stores/settingsStore";
export function CampaignEditor({ initial, grammar, vocabulary }: { initial: Campaign; grammar: GrammarTopic[]; vocabulary: VocabularyItem[] }) {
  const [campaign,setCampaign]=useState(initial); const [selected,setSelected]=useState(initial.chapters[0]?.quests[0]?.scenes[0]?.id); const [validation,setValidation]=useState<ValidationResult>(); const [busy,setBusy]=useState(false);
  const [drafts,setDrafts]=useState<Scene[]>([]); const { getLlmConfigOrUndefined } = useSettingsStore();
  const scene = campaign.chapters.flatMap(c=>c.quests).flatMap(q=>q.scenes).find(s=>s.id===selected);
  const updateScene=(next:Scene)=>setCampaign({...campaign,chapters:campaign.chapters.map(c=>({...c,quests:c.quests.map(q=>({...q,scenes:q.scenes.map(s=>s.id===next.id?next:s)}))}))});
  const validate=async()=>{setBusy(true);try{setValidation(await editorApi.validate(campaign));}finally{setBusy(false)}}; const save=async()=>{setBusy(true);try{const r=await editorApi.saveCampaign(campaign);setValidation(r.validation);}finally{setBusy(false)}};
  const generate=async()=>{if(!scene)return;const llmConfig=getLlmConfigOrUndefined();if(!llmConfig){alert("Önce Systema bölümünden LLM'i etkinleştir.");return;}setBusy(true);try{const r=await editorApi.generateDraft({grammarIds:scene.learningFocus?.grammarIds??[],vocabularyIds:scene.learningFocus?.vocabularyIds??[],locationId:scene.locationId??"",npcIds:scene.npcIds??[],difficulty:scene.learningFocus?.difficulty??"practice",count:1,llmConfig});setDrafts(r.drafts);setValidation(r.validation);}finally{setBusy(false)}};
  return <div className="campaign-editor"><nav className="campaign-tree"><h2>{campaign.title}</h2>{campaign.chapters.map(c=><details open key={c.id}><summary>{c.title}</summary>{c.quests.map(q=><details key={q.id}><summary>{q.title}</summary>{q.scenes.map(s=><button className={s.id===selected?"active":""} key={s.id} onClick={()=>setSelected(s.id)}>{s.title}</button>)}</details>)}</details>)}</nav><main>{scene?<SceneEditor scene={scene} grammar={grammar} vocabulary={vocabulary} onChange={updateScene}/>:<p>Sahne seç.</p>}</main><aside><div className="editor-actions"><button disabled={busy} onClick={()=>void validate()}>Validate</button><button disabled={busy||!validation?.ok} onClick={()=>void save()}>Kaydet</button><button disabled={busy||!scene} onClick={()=>void generate()}>LLM ile sahne taslağı üret</button></div>{drafts.length?<section><h3>Draft JSON Preview</h3><pre>{JSON.stringify(drafts,null,2)}</pre><p>İlk sürümde kampanyaya ekleme manueldir.</p></section>:null}<ValidationPanel result={validation}/></aside></div>;
}
