import { useState } from "react";
import { completeChallenge, startChallenge, submitChallengeAnswer } from "../../api/assessmentApi";
import { useGameStore } from "../../stores/gameStore";
import type { AssessmentAttempt, AssessmentResult } from "../../types/assessmentTypes";
import { AssessmentQuestionCard } from "./AssessmentQuestionCard";
import { AssessmentResultModal } from "./AssessmentResultModal";
type ChallengeType = "grammar" | "vocabulary" | "mixed" | "review" | "quick";
export function ChallengeModePanel() { const { currentSaveId, loadGame } = useGameStore(); const [attempt, setAttempt] = useState<AssessmentAttempt | null>(null); const [result, setResult] = useState<AssessmentResult | null>(null); const [type, setType] = useState<ChallengeType>("quick"); const [loading, setLoading] = useState(false); const current = attempt?.questions.find((question) => !attempt.answers.some((answer) => answer.questionId === question.id)); async function begin(nextType = type) { if (!currentSaveId) return; setLoading(true); const response = await startChallenge({ saveId: currentSaveId, type: nextType, questionCount: nextType === "quick" ? 5 : 8 }); setAttempt(response.attempt); setResult(null); setLoading(false); } async function answer(payload: { answerText?: string; selectedChoice?: string }) { if (!currentSaveId || !attempt || !current) return; setLoading(true); const response = await submitChallengeAnswer({ saveId: currentSaveId, attemptId: attempt.id, questionId: current.id, ...payload }); setAttempt(response.attempt); setLoading(false); } async function finish() { if (!currentSaveId || !attempt) return; setLoading(true); const response = await completeChallenge(currentSaveId, attempt.id); setResult(response.result); await loadGame(currentSaveId); setAttempt(null); setLoading(false); } return <div className="panel-stack"><div className="panel-card"><div className="panel-kicker">Challenge</div><h3>Exercitatio</h3><select value={type} onChange={(event) => setType(event.target.value as ChallengeType)}><option value="quick">Quick</option><option value="mixed">Mixed</option><option value="grammar">Grammar</option><option value="vocabulary">Vocabulary</option><option value="review">Review</option></select><button className="primary-action" onClick={() => begin()} disabled={loading}>Challenge Başlat</button></div>{current ? <AssessmentQuestionCard question={current} disabled={loading} onSubmit={answer} /> : attempt ? <button className="primary-action" onClick={finish} disabled={loading}>Challenge Tamamla</button> : null}<AssessmentResultModal result={result} /></div>; }

