import { VpBadge, VpButton } from "../../ui";
import { ConditionEditor } from "./ConditionEditor";
import { EffectEditor } from "./EffectEditor";
import { SelectField, TextField } from "./editorUtils";

export function ChoiceListEditor({ choices = [], onChange, sceneIds = [], npcIds = [], locationIds = [], skillIds = [], itemIds = [], questIds = [] }: { choices?: any[]; onChange: (choices: any[]) => void; sceneIds?: string[]; npcIds?: string[]; locationIds?: string[]; skillIds?: string[]; itemIds?: string[]; questIds?: string[] }) {
  const update = (index: number, patch: any) => onChange(choices.map((choice, i) => i === index ? { ...choice, ...patch } : choice));
  const move = (index: number, direction: number) => { const next = [...choices]; const [item] = next.splice(index, 1); next.splice(Math.max(0, index + direction), 0, item); onChange(next); };
  return <div className="authoring-nested-editor"><div className="authoring-toolbar"><VpButton type="button" variant="ghost" onClick={() => onChange([...choices, { id: `choice_${choices.length + 1}`, label: "Yeni secim", nextSceneId: "" }])}>Choice ekle</VpButton></div>{choices.map((choice, index) => <div className="authoring-repeat-row" key={choice.id ?? index} data-field-path={`choices.${index}.nextSceneId`}><div className="authoring-row-head"><strong>{choice.label}</strong>{String(choice.label ?? "").length > 80 ? <VpBadge variant="gold">Uzun label</VpBadge> : null}<button type="button" onClick={() => move(index, -1)}>Yukari</button><button type="button" onClick={() => move(index, 1)}>Asagi</button><button type="button" onClick={() => onChange(choices.filter((_, i) => i !== index))}>Sil</button></div><div className="authoring-form-grid"><TextField label="id" value={choice.id} onChange={(id) => update(index, { id })} /><TextField label="label" value={choice.label} onChange={(label) => update(index, { label })} /><TextField label="description" value={choice.description} onChange={(description) => update(index, { description })} /><SelectField label="nextSceneId" value={choice.nextSceneId} options={sceneIds} onChange={(nextSceneId) => update(index, { nextSceneId })} /><VpBadge variant={sceneIds.includes(choice.nextSceneId) ? "success" : "red"}>edge</VpBadge></div><ConditionEditor conditions={choice.conditions ?? []} onChange={(conditions) => update(index, { conditions })} sceneIds={sceneIds} npcIds={npcIds} locationIds={locationIds} skillIds={skillIds} itemIds={itemIds} /><EffectEditor effects={choice.effects ?? []} onChange={(effects) => update(index, { effects })} sceneIds={sceneIds} npcIds={npcIds} locationIds={locationIds} skillIds={skillIds} itemIds={itemIds} questIds={questIds} /></div>)}</div>;
}
