import { VpBadge, VpButton } from "../../ui";
import { JsonAdvancedEditor } from "./JsonAdvancedEditor";
import { EFFECT_TYPES, NumberField, SelectField, TextField, split } from "./editorUtils";

export function EffectEditor({ effects = [], onChange, sceneIds = [], npcIds = [], locationIds = [], skillIds = [], itemIds = [], questIds = [] }: { effects?: any[]; onChange: (effects: any[]) => void; sceneIds?: string[]; npcIds?: string[]; locationIds?: string[]; skillIds?: string[]; itemIds?: string[]; questIds?: string[] }) {
  const update = (index: number, patch: any) => onChange(effects.map((effect, i) => i === index ? { ...effect, ...patch } : effect));
  return <div className="authoring-nested-editor"><div className="authoring-toolbar"><VpButton type="button" variant="ghost" onClick={() => onChange([...effects, { type: "ADD_XP", amount: 10 }])}>Effect ekle</VpButton></div>{effects.map((effect, index) => {
    const unknown = !EFFECT_TYPES.includes(effect?.type);
    const highReward = ["ADD_XP", "ADD_CURRENCY"].includes(effect?.type) && Number(effect?.amount ?? 0) > (effect.type === "ADD_XP" ? 150 : 100);
    return <div className="authoring-repeat-row" key={`${effect?.type}-${index}`}><div className="authoring-row-head"><strong>#{index + 1}</strong>{unknown ? <VpBadge variant="red">JSON</VpBadge> : null}{highReward ? <VpBadge variant="gold">Yuksek odul</VpBadge> : null}<button type="button" onClick={() => onChange(effects.filter((_, i) => i !== index))}>Sil</button></div><div className="authoring-form-grid"><SelectField label="type" value={effect?.type} options={EFFECT_TYPES} onChange={(type) => update(index, { type })} />{renderEffectFields(effect, (patch) => update(index, patch), { sceneIds, npcIds, locationIds, skillIds, itemIds, questIds })}</div><JsonAdvancedEditor value={effect} onChange={(value) => update(index, value)} /></div>;
  })}</div>;
}

function renderEffectFields(effect: any, onChange: (patch: any) => void, ids: { sceneIds: string[]; npcIds: string[]; locationIds: string[]; skillIds: string[]; itemIds: string[]; questIds: string[] }) {
  switch (effect?.type) {
    case "ADD_XP": case "ADD_CURRENCY": case "REMOVE_CURRENCY": return <NumberField label="amount" value={effect.amount} min={0} max={effect.type === "ADD_XP" ? 500 : 250} onChange={(amount) => onChange({ amount })} />;
    case "ADD_ITEM": case "REMOVE_ITEM": return <><SelectField label="itemId" value={effect.itemId} options={ids.itemIds} onChange={(itemId) => onChange({ itemId })} /><NumberField label="quantity" value={effect.quantity ?? 1} min={1} max={99} onChange={(quantity) => onChange({ quantity })} /></>;
    case "UNLOCK_SKILL": case "INCREMENT_SKILL": return <><SelectField label="skillId" value={effect.skillId} options={ids.skillIds} onChange={(skillId) => onChange({ skillId })} />{effect.type === "INCREMENT_SKILL" ? <NumberField label="amount" value={effect.amount ?? 1} min={1} max={10} onChange={(amount) => onChange({ amount })} /> : null}</>;
    case "START_QUEST": case "COMPLETE_QUEST": return <SelectField label="questId" value={effect.questId} options={ids.questIds} onChange={(questId) => onChange({ questId })} />;
    case "GO_TO_SCENE": return <><SelectField label="targetSceneId" value={effect.targetSceneId ?? effect.sceneId} options={ids.sceneIds} onChange={(targetSceneId) => onChange({ targetSceneId })} /><VpBadge variant={ids.sceneIds.includes(effect.targetSceneId ?? effect.sceneId) ? "success" : "red"}>{ids.sceneIds.includes(effect.targetSceneId ?? effect.sceneId) ? "valid" : "missing"}</VpBadge></>;
    case "MARK_SCENE_COMPLETED": return <SelectField label="sceneId" value={effect.sceneId} options={ids.sceneIds} onChange={(sceneId) => onChange({ sceneId })} />;
    case "ADD_NPC_MEMORY": return <><SelectField label="npcId" value={effect.npcId} options={ids.npcIds} onChange={(npcId) => onChange({ npcId })} /><TextField label="text" value={effect.text} onChange={(text) => onChange({ text })} /><NumberField label="importance" value={effect.importance ?? 30} min={1} max={100} onChange={(importance) => onChange({ importance })} /><TextField label="tags" value={(effect.tags ?? []).join(", ")} onChange={(value) => onChange({ tags: split(value) })} /><SelectField label="relatedQuestId" value={effect.relatedQuestId} options={ids.questIds} onChange={(relatedQuestId) => onChange({ relatedQuestId })} /><SelectField label="relatedSceneId" value={effect.relatedSceneId} options={ids.sceneIds} onChange={(relatedSceneId) => onChange({ relatedSceneId })} /></>;
    case "UPDATE_NPC_RELATIONSHIP": return <><SelectField label="npcId" value={effect.npcId} options={ids.npcIds} onChange={(npcId) => onChange({ npcId })} /><NumberField label="trust delta" value={effect.trustDelta ?? effect.delta?.trust ?? 0} min={-100} max={100} onChange={(trustDelta) => onChange({ trustDelta })} /><NumberField label="respect delta" value={effect.respectDelta ?? effect.delta?.respect ?? 0} min={-100} max={100} onChange={(respectDelta) => onChange({ respectDelta })} /><NumberField label="familiarity delta" value={effect.familiarityDelta ?? effect.delta?.familiarity ?? 0} min={-100} max={100} onChange={(familiarityDelta) => onChange({ familiarityDelta })} /><TextField label="reasonTr" value={effect.reasonTr ?? effect.reason} onChange={(reasonTr) => onChange({ reasonTr })} /></>;
    case "DISCOVER_LOCATION": case "SET_LOCATION_MOOD": return <SelectField label="locationId" value={effect.locationId} options={ids.locationIds} onChange={(locationId) => onChange({ locationId })} />;
    case "SET_FLAG": case "SET_NARRATIVE_FLAG": case "SET_LOCATION_FLAG": return <><TextField label="key" value={effect.key ?? effect.flag} onChange={(key) => onChange({ key })} /><TextField label="value" value={effect.value} onChange={(value) => onChange({ value })} /></>;
    default: return <TextField label="payload" value={effect.payload ? JSON.stringify(effect.payload) : ""} onChange={(payload) => onChange({ payload })} />;
  }
}
