import { Play, Trash, ArrowClockwise } from "@phosphor-icons/react";
import { useState } from "react";
import { VpBadge, VpButton, VpCard, VpEmptyState, VpInput, VpSectionHeader } from "../ui";
import { useAuthoringStore } from "../../stores/authoringStore";
import { PreviewStateDiff } from "./PreviewStateDiff";

export function PlaytestPreview() {
  const { previewSession, selectedDocument, startPreviewSession, sendPreviewAction, resetPreviewSession, discardPreviewSession } = useAuthoringStore();
  const [answer, setAnswer] = useState("");
  const scene = previewSession?.state?.currentScene;
  return <VpCard variant="compact" className="authoring-side-card"><VpSectionHeader eyebrow="Preview" title="Playtest v2" /><div className="authoring-chip-row"><VpBadge variant="success">Preview mode</VpBadge>{previewSession ? <VpBadge>{previewSession.source.kind}</VpBadge> : null}</div><div className="authoring-toolbar"><VpButton variant="ghost" icon={<Play size={17} />} disabled={!selectedDocument || !["scene", "quest"].includes(selectedDocument.kind)} onClick={() => void startPreviewSession()}>Baslat</VpButton><VpButton variant="ghost" icon={<ArrowClockwise size={17} />} disabled={!previewSession} onClick={() => void resetPreviewSession()}>Reset</VpButton><VpButton variant="ghost" icon={<Trash size={17} />} disabled={!previewSession} onClick={() => void discardPreviewSession()}>Discard</VpButton></div>{scene ? <div className="authoring-preview"><strong>{scene.titleTr ?? scene.title}</strong><p>{scene.descriptionTr ?? scene.description}</p>{scene.choices?.length ? <div className="authoring-preview-actions">{scene.choices.map((choice: any) => <VpButton key={choice.id} type="button" variant="ghost" onClick={() => void sendPreviewAction({ type: "CHOICE_SELECT", choiceId: choice.id })}>{choice.label}</VpButton>)}</div> : null}{scene.textChallenge ? <form className="authoring-preview-answer" onSubmit={(event) => { event.preventDefault(); void sendPreviewAction({ type: "TEXT_SUBMIT", text: answer }); setAnswer(""); }}><code>{scene.textChallenge.promptTr ?? scene.textChallenge.prompt}</code><VpInput value={answer} onChange={(event) => setAnswer(event.target.value)} /><VpButton type="submit" variant="primary">Gonder</VpButton></form> : null}<PreviewStateDiff diff={previewSession?.stateDiff} /><details><summary>Event log</summary><ul className="authoring-event-log">{(previewSession?.recentEvents ?? []).map((event: any) => <li key={event.id ?? `${event.type}-${event.timestamp}`}><strong>{event.type}</strong><small>{event.timestamp}</small></li>)}</ul></details></div> : <VpEmptyState title="Preview yok">Scene veya quest secildiginde gercek motorla test baslatilabilir.</VpEmptyState>}</VpCard>;
}
