import { randomUUID } from "node:crypto";
import type { GameEvent, PlayerSave, WorldJournalEntry } from "../types/gameTypes";
import { getWorldPresence, normalizeWorldPresence } from "./WorldPresenceState";
export class JournalSystem {
  createJournalEntry(params: { save: PlayerSave; mode: "manual" | "auto_day_summary" | "event_reflection"; relatedNpcIds?: string[]; relatedLocationIds?: string[]; relatedActivityIds?: string[]; learnedWordIds?: string[]; rawFactsTr: string[] }): { save: PlayerSave; entry: WorldJournalEntry; events: GameEvent[] } { if (!params.rawFactsTr.some(Boolean)) throw new Error("Bugün henüz deftere geçecek kadar şey yaşamadın."); const day = params.save.villageLife?.dayState.dayNumber ?? 1; const time = params.save.villageLife?.dayState.timeOfDay ?? "mane"; const entry: WorldJournalEntry = { id: randomUUID(), dayNumber: day, timeOfDay: time, titleTr: `Gün ${day} · ${this.timeLabel(time)}`, bodyTr: `Bugün ${params.rawFactsTr.join(" ")}`, relatedNpcIds: params.relatedNpcIds ?? [], relatedLocationIds: params.relatedLocationIds ?? [], learnedWordIds: params.learnedWordIds ?? [], relatedActivityIds: params.relatedActivityIds ?? [], createdAt: new Date().toISOString(), generatedBy: "template" }; const world = getWorldPresence(params.save); const save = { ...params.save, worldPresence: normalizeWorldPresence({ ...world, journalEntries: [...world.journalEntries, entry] }) }; return { save, entry, events: [{ id: randomUUID(), type: "WORLD_JOURNAL_WRITTEN", timestamp: entry.createdAt, payload: { entryId: entry.id, dayNumber: day } }] }; }
  getJournalEntries(save: PlayerSave): WorldJournalEntry[] { return getWorldPresence(save).journalEntries; }
  generateDaySummary({ save, dayNumber }: { save: PlayerSave; dayNumber: number }): WorldJournalEntry { const facts = save.eventLog.filter(e => Number(e.payload.dayNumber ?? dayNumber) === dayNumber).slice(-5).map(e => String(e.payload.summaryTr ?? e.type)); return this.createJournalEntry({ save, mode: "auto_day_summary", rawFactsTr: facts.length ? facts : ["köyün seslerini dinledim ve günü geride bıraktım."] }).entry; }
  private timeLabel(time: string) { return ({mane:"Sabah",meridies:"Öğle",vesper:"Akşam",nox:"Gece"} as Record<string,string>)[time] ?? time; }
}
