import fs from "node:fs"; import path from "node:path";
import type { NpcMood, PlayerSave } from "../types/gameTypes";
import { WorldPresenceContentLoader } from "./WorldPresenceContentLoader";
import { getWorldPresence } from "./WorldPresenceState";
export class NpcMoodSystem {
  constructor(private readonly loader = new WorldPresenceContentLoader(), private readonly dataRoot = path.resolve(process.cwd(), "data")) {}
  getNpcMood({ save, npcId }: { save: PlayerSave; npcId: string; locationId?: string }): { mood: NpcMood; visibleHintTr: string } { const day = save.villageLife?.dayState.dayNumber ?? 1; const override = getWorldPresence(save).npcMoodOverrides?.[npcId]; if (override && (!override.untilDay || day <= override.untilDay)) return { mood: override.mood, visibleHintTr: override.reasonTr }; const p = this.loader.load().npcMoodProfiles.find(x => x.npcId === npcId); if (!p) return { mood: "thoughtful", visibleHintTr: "Sessizce çevresini izliyor." }; const time = save.villageLife?.dayState.timeOfDay; const rule = [...p.moodRules].filter(r => !r.timeWindows?.length || (!!time && r.timeWindows.includes(time))).sort((a,b)=>b.priority-a.priority)[0]; return { mood: rule?.mood ?? p.defaultMood, visibleHintTr: rule?.visibleHintTr ?? p.defaultHintTr ?? "Her zamanki tavrında görünüyor." }; }
  getNpcPresenceWithMood({ save, locationId }: { save: PlayerSave; locationId: string }) { const scheduleFile = path.join(this.dataRoot,"village","npc-presence.json"); const schedule = fs.existsSync(scheduleFile) ? JSON.parse(fs.readFileSync(scheduleFile,"utf8")) as Record<string,Record<string,string>> : {}; const time = save.villageLife?.dayState.timeOfDay ?? "mane"; const npcs = JSON.parse(fs.readFileSync(path.join(this.dataRoot,"npcs.json"),"utf8")) as {id:string;name:string}[]; return Object.keys(schedule).filter(id => schedule[id]?.[time] === locationId).map(id => { const mood = this.getNpcMood({save,npcId:id,locationId}); return { id, nameTr: npcs.find(n=>n.id===id)?.name ?? id, mood: mood.mood, moodHintTr: mood.visibleHintTr }; }); }
  setTemporaryNpcMood({ save, npcId, mood, untilDay, reasonTr }: { save: PlayerSave; npcId: string; mood: NpcMood; untilDay?: number; reasonTr: string }): PlayerSave { const world = getWorldPresence(save); return { ...save, worldPresence: { ...world, npcMoodOverrides: { ...(world.npcMoodOverrides ?? {}), [npcId]: { mood, untilDay, reasonTr } } } }; }
}
