import type { FreeformActionKind, PlayerSave, RpgSkillId } from "../types/gameTypes";
import { EMPTY_RPG_SKILLS } from "../character/CharacterTypes";
import { WorldPresenceContentLoader } from "./WorldPresenceContentLoader";
import { LocationMemorySystem } from "./LocationMemorySystem";
import { LatinDiscoverySystem } from "./LatinDiscoverySystem";
import { VillageRumorSystem } from "./VillageRumorSystem";
import { NpcMoodSystem } from "./NpcMoodSystem";
import type { WorldContextPack } from "./WorldPresenceTypes";
export class WorldContextBuilder {
  constructor(private readonly loader = new WorldPresenceContentLoader(), private readonly memory = new LocationMemorySystem(), private readonly latin = new LatinDiscoverySystem(loader), private readonly rumors = new VillageRumorSystem(loader), private readonly moods = new NpcMoodSystem(loader)) {}
  buildWorldContext(params: { save: PlayerSave; mode: WorldContextPack["mode"]; sceneId?: string; flowId?: string; nodeId?: string; locationId?: string; npcIds?: string[]; objectId?: string; includeRumors?: boolean; includeLatinFocus?: boolean }): WorldContextPack { const { save } = params; const profile = save.characterProfile; const day = save.villageLife?.dayState ?? { dayNumber:1,timeOfDay:"mane" as const,completedDailyActivityIds:[] }; const location = params.locationId ? this.loader.load().locations.find(l=>l.locationId===params.locationId) : undefined; const objects = location ? this.loader.load().ambientObjects.filter(o=>o.locationId===location.locationId).slice(0,8) : []; const readable = location ? this.loader.load().readableObjects.filter(o=>o.locationId===location.locationId).slice(0,8) : []; const memory = params.locationId ? this.memory.getLocationMemoryView({save,locationId:params.locationId}) : undefined; const npcs = params.locationId ? this.moods.getNpcPresenceWithMood({save,locationId:params.locationId}) : []; const mood = location?.moodByTime?.[day.timeOfDay] ?? location?.defaultMood ?? "quiet"; const availableRumors = params.includeRumors === false ? [] : this.rumors.getAvailableRumors({save,locationId:params.locationId}).slice(0,5); const skills = { ...EMPTY_RPG_SKILLS, ...(profile?.skills ?? {}) } as Record<RpgSkillId,number>;
    return { mode: params.mode, player: { name: save.playerName, origin: profile?.origin ?? "unknown_origin", traits: profile?.traits ?? [], skills, currentLifePhase: profile?.currentLifePhase ?? "village_youth" }, village: { dayNumber: day.dayNumber, timeOfDay: day.timeOfDay, mood, recentActivities: day.completedDailyActivityIds.slice(-8), recentEvents: save.eventLog.slice(-8).map(e=>String(e.payload.summaryTr ?? e.type)) }, location: location ? { id: location.locationId, nameTr: location.nameTr ?? location.locationId, mood, visitCount: memory?.visitCount ?? 0, baseDescriptionTr: location.baseDescriptionTr, visibleObjectIds: objects.map(o=>o.id), readableObjectIds: readable.map(o=>o.id), ambientDetailsTr: objects.slice(0,3).map(o=>o.descriptionTr), memoryNotesTr: memory?.memoryNotesTr.slice(-10) ?? [] } : undefined, npcsPresent: npcs.map(n=>{ const p=this.loader.load().npcMoodProfiles.find(x=>x.npcId===n.id); const mem=save.npcMemories.find(m=>m.npcId===n.id); return { id:n.id,nameTr:n.nameTr,mood:n.mood,relationshipSummaryTr:mem?`Tanışıklık ${mem.relationship.familiarity}/100`:undefined,memorySnippetsTr:(mem?.facts??[]).slice(-5).map(f=>f.text),voiceProfileTr:p?.voiceProfileTr??"Kısa ve doğal konuşur.",voiceProfileLatin:p?.voiceProfileLatin??"Basit Latince kullanır." }; }), rumors: availableRumors.map(r=>({id:r.id,bodyTr:r.bodyTr,sourceNpcId:r.sourceNpcId})), latinFocus: { knownWords: params.includeLatinFocus===false?[]:this.latin.getKnownWorldWords(save).slice(-10), targetWords: location?.latinFocus?.targetWordIds?.slice(0,8)??[], recentMistakes:(save.errorMemory??[]).slice(-5).map(e=>e.tag), grammarFocus:location?.latinFocus?.targetGrammarIds?.slice(0,5)??[],maxLevel:location?.latinFocus?.difficulty??"beginner" }, availableActions: (location?.allowedFreeformActionKinds??[]).map((kind:FreeformActionKind)=>({id:kind,labelTr:this.label(kind),actionKind:kind,requiresLatin:false})), hardConstraints: { allowedNpcIds:npcs.map(n=>n.id),allowedObjectIds:[...objects.map(o=>o.id),...readable.map(o=>o.id)],allowedLocationIds:params.locationId?[params.locationId]:[],forbiddenClaimsTr:["ödül kazandın","görev tamamlandı","yol açıldı","seviye atladın"] } };
  }
  private label(k:FreeformActionKind){return ({inspect_object:"Nesneyi incele",read_text:"Yazıyı oku",listen:"Çevreyi dinle",journal:"Deftere yaz",remember:"Hatırla",speak_to_npc:"Konuş"} as Record<string,string>)[k]??k;}
}
