import { randomUUID } from "node:crypto";
import type { AnalyticsSnapshot, LearningAnalyticsSummary } from "./AssessmentTypes";
import type { PlayerSave } from "../game/types/gameTypes";

export function buildAnalyticsSummary(params: { save: PlayerSave; range: "session" | "daily" | "weekly" | "all-time" }): LearningAnalyticsSummary {
  const events = filterEvents(params.save, params.range); let xpGained = 0, currencyGained = 0, correctAnswers = 0, wrongAnswers = 0;
  const errors: Record<string, number> = {}; const practiced: Record<string, number> = {}; const masteryChanges = new Map<string, LearningAnalyticsSummary["masteryChanges"][number]>();
  for (const event of events) { const p = event.payload ?? {}; if (event.type === "XP_ADDED" && typeof p.amount === "number") xpGained += p.amount; if (event.type === "CURRENCY_ADDED" && typeof p.amount === "number") currencyGained += p.amount; if ((event.type === "TEXT_EVALUATED" || event.type === "PLACEMENT_ANSWERED" || event.type === "CHALLENGE_ANSWERED") && typeof p.isCorrect === "boolean") p.isCorrect ? correctAnswers++ : wrongAnswers++; if (event.type === "MASTERY_UPDATED" && typeof p.targetId === "string" && typeof p.targetType === "string") masteryChanges.set(String(p.targetType) + ":" + p.targetId, { targetId: p.targetId, targetType: p.targetType as "grammar" | "vocabulary" | "skill", before: typeof p.before === "number" ? p.before : undefined, after: typeof p.after === "number" ? p.after : 0 }); }
  for (const attempt of params.save.assessmentAttempts) for (const question of attempt.questions) for (const id of question.grammarIds) practiced[id] = (practiced[id] ?? 0) + 1;
  for (const attempt of params.save.assessmentAttempts) for (const answer of attempt.answers) for (const tag of answer.errorTags) errors[tag] = (errors[tag] ?? 0) + 1;
  const grammarStates = params.save.masteryStates.filter((state) => state.targetType === "grammar");
  return { xpGained, currencyGained, completedScenes: params.save.completedSceneIds.length, completedQuests: Object.values(params.save.questStates).filter((quest) => quest.status === "completed").length + params.save.generatedQuests.filter((quest) => quest.status === "completed").length, correctAnswers, wrongAnswers, accuracy: correctAnswers + wrongAnswers ? Math.round((correctAnswers / (correctAnswers + wrongAnswers)) * 100) : 0, mostPracticedGrammarIds: topCounts(practiced), weakestGrammarIds: grammarStates.filter((state) => state.mastery < 55).sort((a, b) => a.mastery - b.mastery).map((state) => state.targetId).slice(0, 5), strongestGrammarIds: grammarStates.filter((state) => state.mastery >= 75).sort((a, b) => b.mastery - a.mastery).map((state) => state.targetId).slice(0, 5), mostCommonErrorTags: Object.entries(errors).sort((a, b) => b[1] - a[1]).slice(0, 8).map(([tag, count]) => ({ tag, count })), masteryChanges: [...masteryChanges.values()] };
}
export function createAnalyticsSnapshot(params: { save: PlayerSave; range: "session" | "daily" | "weekly" | "all-time" }): PlayerSave { const snapshot: AnalyticsSnapshot = { id: randomUUID(), createdAt: new Date().toISOString(), range: params.range, summary: buildAnalyticsSummary(params) }; return { ...params.save, analyticsSnapshots: [...params.save.analyticsSnapshots, snapshot].slice(-50) }; }
export function getProgressTrend(params: { save: PlayerSave; targetType?: "grammar" | "vocabulary" | "skill"; targetId?: string }): { points: { date: string; value: number }[] } { const points = params.save.analyticsSnapshots.map((snapshot) => ({ date: snapshot.createdAt, value: params.targetId ? snapshot.summary.masteryChanges.find((item) => item.targetId === params.targetId && (!params.targetType || item.targetType === params.targetType))?.after ?? 0 : snapshot.summary.accuracy })); return { points }; }
export function getErrorHeatmap(save: PlayerSave): { tag: string; count: number; relatedGrammarIds: string[] }[] { const map = new Map<string, { count: number; relatedGrammarIds: Set<string> }>(); for (const item of save.errorMemory ?? []) map.set(item.tag, { count: item.count, relatedGrammarIds: new Set(item.relatedGrammarIds) }); return [...map.entries()].map(([tag, value]) => ({ tag, count: value.count, relatedGrammarIds: [...value.relatedGrammarIds] })).sort((a, b) => b.count - a.count); }
export function getMasteryHeatmap(save: PlayerSave): { targetId: string; targetType: "grammar" | "vocabulary" | "skill"; mastery: number; correctCount: number; wrongCount: number }[] { return save.masteryStates.map(({ targetId, targetType, mastery, correctCount, wrongCount }) => ({ targetId, targetType, mastery, correctCount, wrongCount })); }
function filterEvents(save: PlayerSave, range: "session" | "daily" | "weekly" | "all-time") { if (range === "all-time") return save.eventLog; const now = Date.now(); const windowMs = range === "weekly" ? 7 * 86400000 : 86400000; return save.eventLog.filter((event) => now - Date.parse(event.timestamp) <= windowMs); }
function topCounts(counts: Record<string, number>): string[] { return Object.entries(counts).sort((a, b) => b[1] - a[1]).map(([id]) => id).slice(0, 5); }

