import test from "node:test";
import assert from "node:assert/strict";
import type { PlayerSave } from "../game/types/gameTypes";
import { ContentLoader } from "../game/content/ContentLoader";
import { buildChallengeQuestionSet, buildPlacementQuestionSet, getQuestionsByGrammar, loadQuestionBank } from "./AssessmentQuestionBank";
import { scoreAnswer } from "./AssessmentScoringSystem";
import { completePlacementTest, startPlacementTest, submitPlacementAnswer } from "./PlacementTestSystem";
import { getWeaknessReport } from "./DiagnosticSystem";
import { refreshLearningPath } from "./LearningPathSystem";
import { buildAnalyticsSummary } from "./AnalyticsSystem";
import { evaluateAchievements } from "./AchievementSystem";

const loader = new ContentLoader(); loader.load();
function save(): PlayerSave { return { schemaVersion: 5, id: "s", playerName: "P", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), currentCampaignId: "via-prima", currentChapterId: "chapter_ludus", currentQuestId: "quest_prima_dies", currentSceneId: "scene_ludus_intro", level: 1, xp: 0, currency: 0, streak: { current: 0, best: 0 }, masteryStates: [], seenRewardEventIds: [], flags: {}, inventory: [], skills: [], questStates: {}, completedSceneIds: [], visitedSceneIds: [], journalEntries: [], dialogueLog: [], eventLog: [], errorMemory: [], npcMemories: [], locationStates: [], worldEvents: [], activeSideQuestSuggestions: [], narrativeFlags: {}, generatedQuests: [], assessmentAttempts: [], achievements: [], analyticsSnapshots: [] }; }

test("assessment question bank loads and builds unique sets", () => { const bank = loadQuestionBank(); assert.ok(bank.length >= 120); const placement = buildPlacementQuestionSet(); assert.equal(new Set(placement.map((q) => q.id)).size, placement.length); assert.ok(getQuestionsByGrammar(["sum-esse-present"]).length > 0); assert.ok(buildChallengeQuestionSet({ grammarIds: ["greetings"], questionCount: 3 }).length <= 3); });

test("assessment scoring handles deterministic multiple choice", async () => { const question = loadQuestionBank().find((item) => item.type === "multiple-choice")!; const answer = await scoreAnswer({ question, selectedChoice: question.expectedAnswers![0], contentLoader: loader }); assert.equal(answer.isCorrect, true); assert.equal(answer.score, 100); });

test("placement flow completes profile without lowering seeded mastery", async () => { let current = save(); current.masteryStates = [{ targetId: "greetings", targetType: "grammar", seenCount: 1, correctCount: 1, wrongCount: 0, mastery: 90 }]; const started = startPlacementTest({ save: current, questionCount: 3 }); current = started.save; for (const question of started.attempt.questions) { const submitted = await submitPlacementAnswer({ save: current, attemptId: started.attempt.id, questionId: question.id, answerText: question.expectedAnswers?.[0], selectedChoice: question.expectedAnswers?.[0], contentLoader: loader }); current = submitted.save; } const completed = completePlacementTest({ save: current, attemptId: started.attempt.id }); assert.equal(completed.save.assessmentProfile?.placementCompleted, true); assert.ok(completed.result.accuracy >= 90); assert.equal(completed.save.masteryStates.find((state) => state.targetId === "greetings")?.mastery, 90); });

test("diagnostic, learning path, analytics and achievements derive from save", () => { let current = save(); current.masteryStates = [{ targetId: "accusative-basic", targetType: "grammar", seenCount: 2, correctCount: 0, wrongCount: 2, mastery: 20 }]; current.errorMemory = [{ tag: "wrong-case", count: 3, lastSeenAt: new Date().toISOString(), relatedSceneIds: [], relatedGrammarIds: ["accusative-basic"], relatedVocabularyIds: [] }]; current.assessmentProfile = { estimatedLevel: "A1", confidence: 0.8, strengths: [], weaknesses: ["accusative-basic"], grammarScores: { "accusative-basic": 20 }, vocabularyScores: {}, skillScores: {}, lastUpdatedAt: new Date().toISOString(), placementCompleted: true }; const report = getWeaknessReport(current); assert.deepEqual(report.weakGrammarIds, ["accusative-basic"]); current = refreshLearningPath({ save: current, contentLoader: loader }); assert.ok(current.learningPath?.steps.some((step) => step.grammarIds.includes("accusative-basic"))); const summary = buildAnalyticsSummary({ save: current, range: "all-time" }); assert.ok(summary.weakestGrammarIds.includes("accusative-basic")); current = evaluateAchievements(current); assert.equal(current.achievements.find((item) => item.id === "discipulus")?.unlocked, true); });
