import type { ContentLoader } from "../game/content/ContentLoader";
import type { VocabularyItem } from "../game/types/contentTypes";
import { findByLatinForm, findLexicalEntriesByForm, guessLemmaFromForm, loadVocabularyIndex } from "./LatinLemmaService";
import { analyzeAdjectiveForm, analyzeNounForm, analyzeVerbForm, detectCommonFunctionWord, guessNounCandidates, guessVerbCandidates } from "./LatinMorphology";
import { normalizeToken } from "./LatinTokenizer";
import type { LatinFormCandidate, LatinToken, LatinWordAnalysis } from "./LatinTypes";
function analyzeForItem(form: string, item: VocabularyItem): LatinFormCandidate[] { const pos = item.pos.toLowerCase(); if (pos.includes("verb")) return analyzeVerbForm(form, item); if (pos.includes("adjective")) return analyzeAdjectiveForm(form, item); return analyzeNounForm(form, item); }
function unique(candidates: LatinFormCandidate[]): LatinFormCandidate[] { const seen = new Set<string>(); return candidates.filter((c) => { const key = JSON.stringify([c.lemma, c.pos, c.features]); if (seen.has(key)) return false; seen.add(key); return true; }).sort((a, b) => b.confidence - a.confidence); }
export function analyzeWord(params: { token: string; contentLoader: ContentLoader }): LatinWordAnalysis { const normalized = normalizeToken(params.token); const token: LatinToken = { raw: params.token, normalized, index: 0 }; if (!normalized) return { token, candidates: [], warnings: [{ code: "unknown-form", messageTr: "Boş veya çözümlenemeyen biçim." }] }; const candidates: LatinFormCandidate[] = []; const functionWord = detectCommonFunctionWord(normalized); if (functionWord) candidates.push(functionWord); const exact = findByLatinForm(normalized, params.contentLoader); for (const item of exact) { const analyses = analyzeForItem(normalized, item); const fallback: LatinFormCandidate = { lemma: normalizeToken(item.latin), pos: item.pos.includes("verb") ? "verb" : "noun", confidence: .95, source: "vocabulary", meaningTr: item.turkish, vocabularyId: item.id }; candidates.push(...(analyses.length ? analyses : [fallback])); } if (!exact.length) { for (const match of findLexicalEntriesByForm(normalized)) candidates.push({ lemma: match.entry.normalizedLemma, pos: match.entry.pos === "numeral" ? "unknown" : match.entry.pos, confidence: Math.min(.9, match.form.confidence), source: "vocabulary", features: match.form.features, meaningTr: match.entry.meanings.shortTr || match.entry.meanings.shortEn, vocabularyId: match.entry.id }); const index = loadVocabularyIndex(params.contentLoader); const guessed = guessLemmaFromForm(normalized).map((lemma) => index.byLemma.get(lemma)).filter((item): item is VocabularyItem => Boolean(item)); for (const item of guessed) candidates.push(...analyzeForItem(normalized, item)); } if (!candidates.length) candidates.push(...guessVerbCandidates(normalized), ...guessNounCandidates(normalized)); const sorted = unique(candidates); const warnings: LatinWordAnalysis["warnings"] = []; if (!sorted.length) warnings.push({ code: "unknown-form", messageTr: `"${params.token}" için güvenilir çözümleme bulunamadı.` }); else if (sorted.length > 1 && Math.abs(sorted[0].confidence - sorted[1].confidence) < .08) warnings.push({ code: "ambiguous-form", messageTr: "Bu biçim birden fazla gramer çözümüne sahip olabilir." }); if (sorted[0] && sorted[0].confidence < .6) warnings.push({ code: "low-confidence-analysis", messageTr: "Çözümleme sezgiseldir; bağlamla doğrulanmalıdır." }); return { token, candidates: sorted, best: sorted[0], warnings }; }
export function analyzeWords(params: { tokens: LatinToken[]; contentLoader: ContentLoader }): LatinWordAnalysis[] { return params.tokens.map((token) => ({ ...analyzeWord({ token: token.raw, contentLoader: params.contentLoader }), token })); }
