import type { ContentLoader } from "../game/content/ContentLoader";
import { normalizeLatin } from "./LatinNormalizer";
import { analyzeWords } from "./LatinFormAnalyzer";
import { scoreSentenceDifficulty } from "./LatinDifficultyScorer";
import { tokenizeLatin } from "./LatinTokenizer";
import type { LatinDetectedError, LatinDetectedStructure, LatinSentenceAnalysis, LatinWordAnalysis } from "./LatinTypes";
const hasCase = (w: LatinWordAnalysis, value: string) => w.candidates.some((c) => c.features?.case === value);
export function detectStructures(words: LatinWordAnalysis[]): LatinDetectedStructure[] { const out: LatinDetectedStructure[] = []; const forms = words.map((w) => w.token.normalized); const add = (type: LatinDetectedStructure["type"], confidence: number, explanationTr: string, relatedGrammarIds?: string[]) => out.push({ type, confidence, explanationTr, relatedGrammarIds }); if (forms.some((f) => ["salve", "salvete", "ave", "vale", "valete"].includes(f))) add("greeting", .98, "Selamlaşma kalıbı tespit edildi.", ["greetings"]); const sum = words.some((w) => w.best?.lemma === "sum"); if (sum) add("sum-esse", .95, "sum/esse geniş zaman biçimi kullanılıyor.", ["sum-esse-present"]); if (sum && words.some((w) => hasCase(w, "nominative"))) add("simple-nominative-predicate", .72, "Nominativus ile basit yüklem cümlesi olası.", ["nominative-basic", "sum-esse-present"]); const finite = words.some((w) => w.best?.pos === "verb" && w.best.features?.mood === "indicative"); if (finite && words.some((w) => hasCase(w, "nominative")) && words.some((w) => hasCase(w, "accusative"))) add("subject-verb-object", .82, "Özne-fiil-nesne yapısı olası.", ["nominative-basic", "accusative-basic", "present-active-verbs"]); if (words.some((w) => w.best?.features?.mood === "imperative")) add("imperative", .95, "Emir kipi biçimi tespit edildi.", ["imperative-basic"]); if (words.some((w, i) => w.best?.pos === "preposition" && Boolean(words[i + 1]))) add("prepositional-phrase", .72, "Edatlı kelime grubu tespit edildi.", ["basic-prepositions"]); for (let i = 0; i < words.length - 1; i++) { const a = words[i].best; const b = words[i + 1].best; if (a && b && ((a.pos === "noun" && b.pos === "adjective") || (a.pos === "adjective" && b.pos === "noun")) && a.features?.case === b.features?.case && a.features?.number === b.features?.number) { add("noun-adjective-agreement", .7, "İsim ve sıfat uyumu olası.", ["adjective-agreement"]); break; } } return out; }
export function detectPossibleErrors(params: { words: LatinWordAnalysis[]; expectedAnalysis?: LatinSentenceAnalysis; unlockedGrammarIds?: string[] }): LatinDetectedError[] { const errors: LatinDetectedError[] = []; const unknown = params.words.filter((w) => !w.best).length; if (params.words.length >= 3 && !params.words.some((w) => w.best?.pos === "verb")) errors.push({ tag: "missing-verb", severity: "warning", messageTr: "Bu uzunlukta bir cümlede çekimli fiil eksik olabilir." }); if (unknown / Math.max(1, params.words.length) >= .34) errors.push({ tag: "unknown-word", severity: "warning", messageTr: "Cümlenin önemli bir bölümü çözümlenemedi." }); if (params.expectedAnalysis?.detectedStructures.some((s) => s.type === "sum-esse") && !params.words.some((w) => w.best?.lemma === "sum")) errors.push({ tag: "missing-sum", severity: "error", messageTr: "Beklenen sum/esse biçimi görünmüyor.", relatedGrammarIds: ["sum-esse-present"] }); if (params.expectedAnalysis?.detectedStructures.some((s) => s.type === "greeting") && !params.words.some((w) => ["salve", "ave", "vale"].includes(w.best?.lemma || ""))) errors.push({ tag: "missing-greeting", severity: "error", messageTr: "Beklenen selamlaşma sözü görünmüyor.", relatedGrammarIds: ["greetings"] }); return errors; }
export function summaryTr(analysis: Omit<LatinSentenceAnalysis, "summaryTr">): string { const structures = analysis.detectedStructures.map((s) => s.type).join(", ") || "belirgin yapı yok"; const unknown = analysis.words.filter((w) => !w.best).length; return `${analysis.tokens.length} kelime; ${structures}; ${unknown} çözümlenemeyen biçim; zorluk ${analysis.difficulty.level}.`; }
export function analyzeSentence(params: { text: string; contentLoader: ContentLoader; unlockedGrammarIds?: string[]; knownVocabularyIds?: string[]; playerLevel?: number }): LatinSentenceAnalysis { const tokens = tokenizeLatin(params.text); const words = analyzeWords({ tokens, contentLoader: params.contentLoader }); const detectedStructures = detectStructures(words); const analysis: LatinSentenceAnalysis = { original: params.text, normalized: normalizeLatin(params.text), tokens, words, detectedStructures, possibleErrors: [], difficulty: { level: "unknown", score: 0, reasons: [], detectedGrammarIds: [], detectedVocabularyIds: [], outOfLevelGrammarIds: [], outOfLevelVocabularyIds: [] }, summaryTr: "" }; analysis.possibleErrors = detectPossibleErrors({ words, unlockedGrammarIds: params.unlockedGrammarIds }); analysis.difficulty = scoreSentenceDifficulty({ analysis, contentLoader: params.contentLoader, playerLevel: params.playerLevel, allowedGrammarIds: params.unlockedGrammarIds, knownVocabularyIds: params.knownVocabularyIds }); analysis.summaryTr = summaryTr(analysis); return analysis; }
