import type { ContentLoader } from "../game/content/ContentLoader";
import type { Scene } from "../game/types/gameTypes";
import { analyzeSentence } from "./LatinSentenceAnalyzer";
import { levelForPlayer } from "./LatinDifficultyScorer";
import type { GrammarGateResult } from "./LatinTypes";
export function makeSafeSuggestion(params: { original: string; violations: GrammarGateResult["violations"]; fallbackVocabulary?: string[] }): string { const lower = params.original.toLowerCase(); if (lower.includes("salv") || lower.includes("ave")) return "Salve, discipule."; if (lower.includes("sum") || lower.includes("est")) return "Ego sum discipulus."; return params.fallbackVocabulary?.length ? `${params.fallbackVocabulary[0]} intrat.` : "Puer intrat."; }
export function checkTextAgainstLevel(params: { text: string; contentLoader: ContentLoader; playerLevel: number; allowedGrammarIds: string[]; knownVocabularyIds?: string[]; maxSentenceLength?: number }): GrammarGateResult { try { const analysis = analyzeSentence({ text: params.text, contentLoader: params.contentLoader, playerLevel: params.playerLevel, unlockedGrammarIds: params.allowedGrammarIds, knownVocabularyIds: params.knownVocabularyIds }); const violations: GrammarGateResult["violations"] = []; const max = params.maxSentenceLength ?? (params.playerLevel <= 1 ? 6 : 10); if (analysis.tokens.length > max) violations.push({ type: "length", messageTr: `Latince satır ${max} kelimelik sınırı aşıyor.` }); for (const id of analysis.difficulty.outOfLevelGrammarIds) violations.push({ type: "grammar", id, messageTr: `${id} izinli gramer kapsamında değil.` }); const unknown = analysis.words.filter((w) => !w.best || w.best.confidence < .45); if (unknown.length / Math.max(1, analysis.words.length) >= .34) violations.push({ type: "unknown-form", token: unknown.map((w) => w.token.raw).join(", "), messageTr: "Çok sayıda bilinmeyen veya düşük güvenli biçim var." }); if (analysis.difficulty.outOfLevelVocabularyIds.length > 2) violations.push({ type: "vocabulary", messageTr: "Metin bilinen kelime kapsamının belirgin biçimde dışında." }); const ok = violations.length === 0; return { ok, level: levelForPlayer(params.playerLevel), violations, safeSuggestion: ok ? undefined : makeSafeSuggestion({ original: params.text, violations }) }; } catch { return { ok: true, level: levelForPlayer(params.playerLevel), violations: [] }; } }
export function checkSceneLatin(params: { scene: Scene; contentLoader: ContentLoader; playerLevel: number; allowedGrammarIds: string[]; knownVocabularyIds?: string[] }): GrammarGateResult { const texts = params.scene.textChallenge?.expectedAnswers || []; const results = texts.map((text) => checkTextAgainstLevel({ ...params, text })); const violations = results.flatMap((r) => r.violations); return { ok: violations.length === 0, level: levelForPlayer(params.playerLevel), violations, safeSuggestion: violations.length ? results.find((r) => r.safeSuggestion)?.safeSuggestion : undefined }; }

