import type { ContentLoader } from "../game/content/ContentLoader";
import type { Scene } from "../game/types/gameTypes";
import { analyzeSentence } from "./LatinSentenceAnalyzer";
import type { LatinDetectedError, LatinWordAnalysis } from "./LatinTypes";
const feature = (word: LatinWordAnalysis | undefined, key: "case" | "number" | "person" | "tense") => word?.best?.features?.[key];
export function analyzeLatinErrors(params: { playerAnswer: string; expectedAnswers: string[]; contentLoader: ContentLoader; prompt?: string; scene?: Scene; evaluationMode?: "strict" | "normal" | "loose" }): LatinDetectedError[] { const expected = params.expectedAnswers.map((text) => analyzeSentence({ text, contentLoader: params.contentLoader })); const player = analyzeSentence({ text: params.playerAnswer, contentLoader: params.contentLoader }); const target = expected[0]; if (!target) return []; const errors = [...player.possibleErrors]; if (target.detectedStructures.some((s) => s.type === "sum-esse") && !player.words.some((w) => w.best?.lemma === "sum")) errors.push({ tag: "missing-sum", severity: "error", messageTr: "sum/esse fiili eksik görünüyor." }); if (target.detectedStructures.some((s) => s.type === "greeting") && !player.detectedStructures.some((s) => s.type === "greeting")) errors.push({ tag: "missing-greeting", severity: "error", messageTr: "Selamlaşma ifadesi eksik görünüyor." }); const expectedByLemma = new Map(target.words.filter((w) => w.best).map((w) => [w.best!.lemma, w])); for (const word of player.words) { const ew = word.best ? expectedByLemma.get(word.best.lemma) : undefined; if (!ew) continue; if (feature(ew, "case") === "accusative" && feature(word, "case") === "nominative") errors.push({ tag: "accusative-needed", severity: "error", messageTr: `${word.token.raw} için accusativus gerekli olabilir.`, token: word.token.raw, expected: "accusative", actual: "nominative", relatedGrammarIds: ["accusative-basic"] }); else if (feature(ew, "case") && feature(word, "case") && feature(ew, "case") !== feature(word, "case")) errors.push({ tag: "wrong-case", severity: "warning", messageTr: `${word.token.raw} farklı bir hâlde görünüyor.`, token: word.token.raw }); if (feature(ew, "number") && feature(word, "number") && feature(ew, "number") !== feature(word, "number")) errors.push({ tag: "wrong-number", severity: "warning", messageTr: "Tekillik/çoğulluk uyuşmuyor.", token: word.token.raw }); if (feature(ew, "person") && feature(word, "person") && feature(ew, "person") !== feature(word, "person")) errors.push({ tag: "wrong-person", severity: "error", messageTr: "Fiilin kişisi beklenen özneyle uyuşmuyor.", token: word.token.raw }); }
  const playerLemmas = player.words.map((w) => w.best?.lemma).filter(Boolean).sort().join(" "); const expectedLemmas = target.words.map((w) => w.best?.lemma).filter(Boolean).sort().join(" "); if (playerLemmas && playerLemmas === expectedLemmas && player.normalized !== target.normalized) errors.push({ tag: "word-order-variant", severity: "info", messageTr: "Aynı lemma kümesi farklı kelime sırasıyla kullanılmış." }); if (player.words.some((w) => !w.best)) errors.push({ tag: "unknown-word", severity: "warning", messageTr: "Bir veya daha fazla kelime çözümlenemedi." }); return [...new Map(errors.map((e) => [e.tag, e])).values()]; }
export function mapDetectedErrorsToTags(errors: LatinDetectedError[]): string[] { return [...new Set(errors.map((error) => error.tag))]; }

