import type { VocabularyItem } from "../game/types/contentTypes";
import type { LatinCase, LatinFormCandidate, LatinGender, LatinNumber, LatinPos } from "./LatinTypes";
import { normalizeToken } from "./LatinTokenizer";

const fw: Record<string, LatinFormCandidate> = Object.fromEntries([
  ["et", "conjunction"], ["sed", "conjunction"], ["non", "particle"], ["in", "preposition"], ["ad", "preposition"], ["cum", "preposition"], ["sine", "preposition"], ["salve", "interjection"], ["salvete", "interjection"], ["ave", "interjection"], ["vale", "interjection"], ["valete", "interjection"]
].map(([lemma, pos]) => [lemma, { lemma: lemma === "salvete" ? "salve" : lemma === "valete" ? "vale" : lemma, pos: pos as LatinPos, confidence: .95, source: "vocabulary" }]));
fw.ego = { lemma: "ego", pos: "pronoun", confidence: .95, source: "vocabulary", features: { case: "nominative", number: "singular", person: "1" } };
fw.tu = { lemma: "tu", pos: "pronoun", confidence: .95, source: "vocabulary", features: { case: "nominative", number: "singular", person: "2" } };
const sumForms: Record<string, ["1" | "2" | "3", LatinNumber]> = { sum: ["1", "singular"], es: ["2", "singular"], est: ["3", "singular"], sumus: ["1", "plural"], estis: ["2", "plural"], sunt: ["3", "plural"] };
const imperatives: Record<string, string> = { ama: "amo", amate: "amo", vide: "video", videte: "video", duc: "duco", ducite: "duco", audi: "audio", audite: "audio" };
const enrich = (c: LatinFormCandidate, item?: VocabularyItem): LatinFormCandidate => item ? { ...c, lemma: normalizeToken(item.latin), meaningTr: item.turkish, vocabularyId: item.id } : c;
export function detectCommonFunctionWord(form: string): LatinFormCandidate | null { return fw[normalizeToken(form)] || null; }

function nounFeatures(form: string, lemma: string): Array<{ case: LatinCase; number: LatinNumber; gender: LatinGender; declension: string }> {
  const out: Array<{ case: LatinCase; number: LatinNumber; gender: LatinGender; declension: string }> = [];
  const add = (caseName: LatinCase, number: LatinNumber, gender: LatinGender, declension: string) => out.push({ case: caseName, number, gender, declension });
  if (lemma.endsWith("a")) {
    if (form.endsWith("am")) add("accusative", "singular", "feminine", "1"); else if (form.endsWith("arum")) add("genitive", "plural", "feminine", "1"); else if (form.endsWith("as")) add("accusative", "plural", "feminine", "1"); else if (form.endsWith("is")) { add("dative", "plural", "feminine", "1"); add("ablative", "plural", "feminine", "1"); } else if (form.endsWith("ae")) { add("genitive", "singular", "feminine", "1"); add("dative", "singular", "feminine", "1"); add("nominative", "plural", "feminine", "1"); } else if (form.endsWith("a")) { add("nominative", "singular", "feminine", "1"); add("ablative", "singular", "feminine", "1"); }
  } else if (lemma.endsWith("um")) {
    if (form.endsWith("orum")) add("genitive", "plural", "neuter", "2"); else if (form.endsWith("is")) { add("dative", "plural", "neuter", "2"); add("ablative", "plural", "neuter", "2"); } else if (form.endsWith("a")) { add("nominative", "plural", "neuter", "2"); add("accusative", "plural", "neuter", "2"); } else if (form.endsWith("i")) add("genitive", "singular", "neuter", "2"); else if (form.endsWith("o")) { add("dative", "singular", "neuter", "2"); add("ablative", "singular", "neuter", "2"); } else if (form.endsWith("um")) { add("nominative", "singular", "neuter", "2"); add("accusative", "singular", "neuter", "2"); }
  } else {
    if (form.endsWith("orum")) add("genitive", "plural", "masculine", "2"); else if (form.endsWith("os")) add("accusative", "plural", "masculine", "2"); else if (form.endsWith("um")) add("accusative", "singular", "masculine", "2"); else if (form.endsWith("is")) { add("dative", "plural", "masculine", "2"); add("ablative", "plural", "masculine", "2"); } else if (form.endsWith("i")) { add("genitive", "singular", "masculine", "2"); add("nominative", "plural", "masculine", "2"); } else if (form.endsWith("o")) { add("dative", "singular", "masculine", "2"); add("ablative", "singular", "masculine", "2"); } else if (form.endsWith("us") || form === lemma) add("nominative", "singular", "masculine", "2"); else if (lemma.endsWith("us") && form === lemma.slice(0, -2) + "e") add("vocative", "singular", "masculine", "2");
  }
  return out;
}
export function analyzeNounForm(form: string, item?: VocabularyItem): LatinFormCandidate[] { const normalized = normalizeToken(form); const lemma = normalizeToken(item?.latin || normalized); return nounFeatures(normalized, lemma).map((features) => enrich({ lemma, pos: "noun", confidence: item ? .8 : .45, source: item ? "morphology" : "heuristic", features }, item)); }
export function analyzeAdjectiveForm(form: string, item?: VocabularyItem): LatinFormCandidate[] { return analyzeNounForm(form, item).map((c) => ({ ...c, pos: "adjective" })); }
export function analyzeVerbForm(form: string, item?: VocabularyItem): LatinFormCandidate[] { const f = normalizeToken(form); if (sumForms[f]) { const [person, number] = sumForms[f]; return [enrich({ lemma: "sum", pos: "verb", confidence: item ? .95 : .9, source: item ? "vocabulary" : "morphology", features: { person, number, tense: "present", mood: "indicative", voice: "active", conjugation: "irregular" } }, item)]; } if (imperatives[f]) return [enrich({ lemma: imperatives[f], pos: "verb", confidence: item ? .9 : .8, source: "morphology", features: { person: "2", number: f.endsWith("te") ? "plural" : "singular", tense: "present", mood: "imperative", voice: "active" } }, item)]; const endings: Array<[string, "1" | "2" | "3", LatinNumber]> = [["mus", "1", "plural"], ["tis", "2", "plural"], ["nt", "3", "plural"], ["o", "1", "singular"], ["s", "2", "singular"], ["t", "3", "singular"]]; const ending = endings.find(([suffix]) => f.endsWith(suffix)); if (!ending) return []; return [enrich({ lemma: normalizeToken(item?.latin || guessVerbLemma(f)), pos: "verb", confidence: item ? .8 : .45, source: item ? "morphology" : "heuristic", features: { person: ending[1], number: ending[2], tense: "present", mood: "indicative", voice: "active" } }, item)]; }
function guessVerbLemma(form: string): string { if (/(amus|atis|ant|as|at)$/u.test(form)) return form.replace(/(amus|atis|ant|as|at)$/u, "") + "o"; if (/(emus|etis|ent|es|et)$/u.test(form)) return form.replace(/(emus|etis|ent|es|et)$/u, "") + "eo"; if (/(imus|itis|iunt|unt|is|it)$/u.test(form)) return form.replace(/(imus|itis|iunt|unt|is|it)$/u, "") + "o"; return form; }
export function guessNounCandidates(form: string): LatinFormCandidate[] { const f = normalizeToken(form); const lemmas = new Set<string>(); if (/(am|ae|arum|as)$/u.test(f)) lemmas.add(f.replace(/(am|ae|arum|as)$/u, "") + "a"); if (/(um|i|o|orum|is|os)$/u.test(f)) { const stem = f.replace(/(um|i|o|orum|is|os)$/u, ""); lemmas.add(stem + "us"); lemmas.add(stem + "um"); } return [...lemmas].flatMap((lemma) => nounFeatures(f, lemma).map((features) => ({ lemma, pos: "noun", confidence: .45, source: "heuristic", features }))); }
export function guessVerbCandidates(form: string): LatinFormCandidate[] { return analyzeVerbForm(form); }

