import type { ContentLoader } from "../game/content/ContentLoader";
import type { LatinExercise } from "./LatinTypes";
type Params = { grammarIds: string[]; vocabularyIds?: string[]; errorTags?: string[]; count: number; difficulty: LatinExercise["difficulty"]; contentLoader: ContentLoader };
const exercise = (id: string, type: LatinExercise["type"], promptTr: string, expectedAnswers: string[], grammarIds: string[], difficulty: LatinExercise["difficulty"], choices?: string[], explanationTr?: string): LatinExercise => ({ id, type, promptTr, expectedAnswers, choices, grammarIds, vocabularyIds: [], difficulty, explanationTr });
export function generateGreetingExercises(p: Params): LatinExercise[] { return [exercise("greeting-1", "translate-to-latin", "Magister'e Latince selam ver.", ["Salve, magister!"], ["greetings"], p.difficulty), exercise("greeting-2", "choose-form", "Bir kişiye selam vermek için doğru sözü seç.", ["salve"], ["greetings"], p.difficulty, ["salve", "valete", "sum"])]; }
export function generateSumEsseExercises(p: Params): LatinExercise[] { return [exercise("sum-1", "translate-to-latin", "Ben öğrenciyim.", ["Ego discipulus sum.", "Discipulus sum."], ["sum-esse-present", "nominative-basic"], p.difficulty), exercise("sum-2", "fill-blank", "Marcus ___ discipulus.", ["est"], ["sum-esse-present"], p.difficulty, ["sum", "es", "est"])]; }
export function generateAccusativeExercises(p: Params): LatinExercise[] { return [exercise("acc-1", "fill-blank", "Puer ___ videt.", ["puellam"], ["accusative-basic"], p.difficulty, ["puella", "puellam", "puellae"], "Doğrudan nesne accusativus alır."), exercise("acc-2", "parse-word", "puerum hangi hâldedir?", ["accusative", "accusativus"], ["accusative-basic"], p.difficulty)]; }
export function generateNominativeExercises(p: Params): LatinExercise[] { return [exercise("nom-1", "choose-form", "Cümlenin öznesi için doğru biçimi seç: ___ videt.", ["puella"], ["nominative-basic"], p.difficulty, ["puella", "puellam", "puellae"])]; }
export function generateExercises(p: Params): LatinExercise[] { const pool: LatinExercise[] = []; const tags = new Set([...p.grammarIds, ...(p.errorTags || [])]); if (tags.has("greetings") || tags.has("missing-greeting")) pool.push(...generateGreetingExercises(p)); if (tags.has("sum-esse-present") || tags.has("missing-sum")) pool.push(...generateSumEsseExercises(p)); if (tags.has("accusative-basic") || tags.has("accusative-needed") || tags.has("wrong-case")) pool.push(...generateAccusativeExercises(p)); if (tags.has("nominative-basic")) pool.push(...generateNominativeExercises(p)); if (!pool.length) pool.push(...generateGreetingExercises(p), ...generateSumEsseExercises(p)); const count = Math.max(0, Math.min(20, p.count)); return Array.from({ length: count }, (_, i) => ({ ...pool[i % pool.length], id: `${pool[i % pool.length].id}-${i + 1}`, vocabularyIds: p.vocabularyIds || [] })); }

